version: '3.7'

services:
    spotifycharts:
        container_name: spotifycharts
        build:
            dockerfile: dockerfile
            context: ./
        ports:
            - 8001:8000
        entrypoint: uvicorn application.main:api --host 0.0.0.0 --port 8000