name: Main Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:

      - uses: actions/checkout@v2

      - name: Install Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
        if: ${{ success() }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
        if: ${{ success() }}

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 spotifycharts application --count --select=E1,E2,E3,E4,E5,E6,E7,E8,E9,W1,W2,W3,W4,W5,W6,F4,F5,F6,F7,F8,F9 --ignore=E501 --show-source --statistics
        if: ${{ success() }}

      - name: Test with pytest
        run: |
          pip install pytest
          pytest
        if: ${{ success() }}

      - name: Build and publish the package on PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          pip install setuptools wheel
          python setup.py sdist bdist_wheel
          twine upload dist/*
        if: ${{ success() }}
