name: Run Python Package Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest
    steps:

      - uses: actions/checkout@v2

      - if: ${{ success() }}
      - name: Install Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
        run:
          - python -m pip install --upgrade pip

      - if: ${{ success() }}
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - if: ${{ success() }}
      - name: Test with pytest
        run: |
          pip install pytest
          pytest

      - if: ${{ success() }}
      - name: Build and publish the package on PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          pip install setuptools wheel
          python setup.py sdist bdist_wheel
          twine upload dist/*